/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainRun;

import Analizador.Analizador;
import Files.FileDriver;
import object.TokenBag;

/**
 *
 * @author byron
 */
public class AnalizadorFrame extends javax.swing.JFrame {

     TokenBag tokenBag = new TokenBag();
     FileDriver fileDriver = new FileDriver();
     Analizador analizador;

     /**
      * Creates new form AnalizadorFrame
      */
     public AnalizadorFrame() {
          initComponents();
          setLocationRelativeTo(null);
           textIn.setText("");
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING:
      * Do NOT modify this code. The content of this method is always regenerated by the
      * Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          mainPanel = new javax.swing.JPanel();
          jScrollPane2 = new javax.swing.JScrollPane();
          textIn = new javax.swing.JTextArea();
          jScrollPane4 = new javax.swing.JScrollPane();
          tokensOut = new javax.swing.JTextArea();
          analyzerButton = new javax.swing.JButton();
          cleanButton = new javax.swing.JButton();
          exitBotton = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          infoOut = new javax.swing.JTextArea();
          cargaButton = new javax.swing.JButton();
          exportButton = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Analizador Lexico");
          setBackground(new java.awt.Color(13, 65, 99));
          setForeground(java.awt.Color.darkGray);
          setResizable(false);

          textIn.setColumns(20);
          textIn.setLineWrap(true);
          textIn.setRows(5);
          jScrollPane2.setViewportView(textIn);

          tokensOut.setEditable(false);
          tokensOut.setColumns(20);
          tokensOut.setRows(5);
          jScrollPane4.setViewportView(tokensOut);

          analyzerButton.setText("Analizar");
          analyzerButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    analyzerButtonActionPerformed(evt);
               }
          });

          cleanButton.setText("Limpiar");
          cleanButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cleanButtonActionPerformed(evt);
               }
          });

          exitBotton.setText("Salir");
          exitBotton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitBottonActionPerformed(evt);
               }
          });

          infoOut.setEditable(false);
          infoOut.setColumns(20);
          infoOut.setRows(5);
          jScrollPane1.setViewportView(infoOut);

          cargaButton.setText("Cargar");
          cargaButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cargaButtonActionPerformed(evt);
               }
          });

          exportButton.setText("Exportar");
          exportButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exportButtonActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
          mainPanel.setLayout(mainPanelLayout);
          mainPanelLayout.setHorizontalGroup(
               mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(mainPanelLayout.createSequentialGroup()
                              .addComponent(exitBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(exportButton)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(cargaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(analyzerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(11, 11, 11))
                         .addGroup(mainPanelLayout.createSequentialGroup()
                              .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jScrollPane1)
                                   .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap(15, Short.MAX_VALUE))))
          );
          mainPanelLayout.setVerticalGroup(
               mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                         .addComponent(jScrollPane4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(exitBotton)
                         .addComponent(cleanButton)
                         .addComponent(analyzerButton)
                         .addComponent(cargaButton)
                         .addComponent(exportButton))
                    .addContainerGap())
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void cargaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaButtonActionPerformed
          fileDriver.fileReader(cleanButton, textIn);
     }//GEN-LAST:event_cargaButtonActionPerformed

     private void exitBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBottonActionPerformed
          System.exit(0);
     }//GEN-LAST:event_exitBottonActionPerformed

     private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
          textIn.setText("");
          tokensOut.setText("");
          infoOut.setText("");
          tokenBag.clearArrays();
     }//GEN-LAST:event_cleanButtonActionPerformed

     private void analyzerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzerButtonActionPerformed

          analizador = new Analizador(textIn.getText(), tokenBag);
          tokensOut.setText(tokenBag.showTokens());
          infoOut.setText(analizador.getData());
     }//GEN-LAST:event_analyzerButtonActionPerformed

     private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
          //if ("".equals(infoOut.getText())) {
               fileDriver.fileWritter(exportButton, tokensOut);
          //} else {
            //   JOptionPane.showMessageDialog(null, "El no puede ser guardado porque tiene errores");

          //}


     }//GEN-LAST:event_exportButtonActionPerformed

     /**
      * @param args the command line arguments
      */

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton analyzerButton;
     private javax.swing.JButton cargaButton;
     private javax.swing.JButton cleanButton;
     private javax.swing.JButton exitBotton;
     private javax.swing.JButton exportButton;
     private javax.swing.JTextArea infoOut;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane4;
     private javax.swing.JPanel mainPanel;
     private javax.swing.JTextArea textIn;
     private javax.swing.JTextArea tokensOut;
     // End of variables declaration//GEN-END:variables
}
